version: "3"
services:
  myredis:
    image: redis:alpine
  gdanmaku:
    build: .
    image: gdanmaku-server:current
    volumes:
      - ./settings_local.py:/app/gdanmaku/settings_local.py
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert_key:/cert_key
    ports:
      - "80:80"
      - "443:443"
